name: Sample proogram for artifacts

on:
  workflow_dispatch:
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: set up python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Update pip to the latest version
      run: |
        python -m pip install --upgrade pip

    - name: install poetry
      run: |
        pip install poetry
        echo "Poetry installed at:"
        which poetry
        poetry --version
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: install dependencies in python
      run: |
        poetry install --no-root


  run_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: set up python   
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: install poetry
      run: |
        pip install poetry
        echo "Poetry installed at:"
        which poetry
        poetry --version
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: install dependencies in python
      run: |
        poetry install --no-root
  

    - name: Check if pytest is installed
      run: |
        poetry show pytest 

    - name: Install Playwright Browsers
      run: |
          poetry run playwright install
     
    - name: Create a directory for test results
      run: |
          mkdir -p ./test_results 

    - name: run the code
      run: |
          echo "runs the code"
          poetry run pytest automation/tests/login_page_dertails_test/login_page_test_info.py >> ./test_results/result.txt

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
          name: pytest-results
          path: ./test_results/result.txt 
