name: reusable workflow

on:
  workflow_dispatch

jobs:
  use-common-workflow:
    uses: ./.github/workflows/common_workflow.yml  
    with:
       python-version: '3.12'  

  job2:
    needs: use-common-workflow
    runs-on: ubuntu-latest
    steps: 
      - name: running the code
        run: |
            echo "print something"
 
