name: Example Workflow Using Secrets

on: 
  push:
    branches:
      - master

jobs:
  commit_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git username and email from env 
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
        run: |
          git config user.name "$GITHUB_USERNAME"  # Local configuration
          git config user.email "$GITHUB_EMAIL" 
          
      - name: Make changes and commit
        run: |
          echo "Some new change" >> myfile.txt
          git add myfile.txt
          git commit -m "Commit changes automatically"
          git push origin master
