name: Example Workflow Using Secrets

on: 
  push:
    branches:
      - master

jobs:
  commit_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "${{ secrets.GITHUB_USERNAME }}"
          git config user.email "${{ secrets.GITHUB_EMAIL }}"
          
      - name: Make changes and commit
        run: |
          echo "Some new change" >> myfile.txt
          git add myfile.txt
          git commit -m "Commit changes automatically"
          git push origin main
