name: Example Workflow Using Secrets

on: 
  workflow_dispatch

jobs:
  commit_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git username and email
        run: |
          # Set local git config using secrets directly
          git config user.name "${{ github.actor }}"
          git config user.email "${{  github.actor }}@users.noreply.github.com"
          
      - name: Make changes and commit
        run: |
          echo "Some new change" >> myfile.txt
          git add myfile.txt
          git commit -m "Commit changes automatically"
          git push origin master
