name: Sample proogram for dispatch event

on:
  workflow_dispatch:
jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Update pip to the latest version
      run: |
        python -m pip install --upgrade pip

    - name: install poetry
      run: |
        pip install poetry
        # Print installation location
        echo "Poetry installed at:"
        which poetry
        # Print Poetry version
        poetry --version
        # Add Poetry to PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: install dependencies in python
      run: |
        poetry install


  run_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: install poetry
      run: |
        pip install poetry
        # Print installation location
        echo "Poetry installed at:"
        which poetry
        # Print Poetry version
        poetry --version
        # Add Poetry to PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Check if pytest is installed
      run: |
        poetry show pytest 
    
    - name: run the code
      run: |
          echo "runs the code"
          poetry run pytest automation/tests/login_page_dertails_test/login_page_test_info.py --headed

