name: Sample proogram for dispatch event

on:
  workflow_dispatch:
jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: install requirements.txt file
      run: |
        pip install -r requirements.txt

  run_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: run the code
      run: |
          echo "runs the code"
          pytest automation/tests/login_page_dertails_test/login_page_test_info.py --headed

